/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
"use client";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { ThreeElements } from "@react-three/fiber";
import { Group } from "three";

type ForestARModelProps = ThreeElements["group"] & {
    ref?: React.Ref<Group>;
};

export function ForestARModel({ ref, ...props }: ForestARModelProps) {
    const { nodes, materials } = useGLTF("/pine_forest_AR.glb") as any;
    return (
        <group {...props} dispose={null} ref={ref}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_6.geometry}
                material={materials.mat1}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_4.geometry}
                material={materials.pine}
            />
        </group>
    );
}

useGLTF.preload("/pine_forest_AR.glb");
