/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
"use client";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { ThreeElements } from "@react-three/fiber";
import { Group } from "three";

type MetroARModelProps = ThreeElements["group"] & {
    ref?: React.Ref<Group>;
};

export function MetroARModel({ ref, ...props }: MetroARModelProps) {
    const { nodes, materials } = useGLTF("/Metro_AR.glb") as any;
    return (
        <group {...props} dispose={null} ref={ref}>
            <group
                position={[8.097, 2.901, 6.79]}
                rotation={[0, -Math.PI / 2, 0]}
                scale={1.875}
            >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.subway_car_1.geometry}
                    material={materials.metal}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.subway_car_2.geometry}
                    material={materials.metal_01}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.subway_car_3.geometry}
                    material={materials.metal_03}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.subway_car_4.geometry}
                    material={materials.Floor}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.subway_car_5.geometry}
                    material={materials.metal_04}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.subway_car_6.geometry}
                    material={materials.Trains_01}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.subway_car_7.geometry}
                    material={materials.metal_02}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.subway_car_8.geometry}
                    material={materials.Trains}
                />
            </group>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.seats.geometry}
                material={materials.seats}
                position={[9.616, 1.922, 3.257]}
                scale={-0.031}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.seats001.geometry}
                material={materials.seats}
                position={[9.616, 1.922, -2.061]}
                scale={-0.031}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Railing_V.geometry}
                material={materials.metal_05}
                position={[9.343, 3.268, 3.295]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Railing_V001.geometry}
                material={materials.metal_05}
                position={[9.389, 3.084, -2.056]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.seats002.geometry}
                material={materials.seats}
                position={[9.616, 1.922, 10.231]}
                scale={-0.031}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Railing_V002.geometry}
                material={materials.metal_05}
                position={[9.343, 3.268, 10.269]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.seats003.geometry}
                material={materials.seats}
                position={[9.616, 1.922, 15.64]}
                scale={-0.031}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Railing_V003.geometry}
                material={materials.metal_05}
                position={[9.389, 3.084, 15.645]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.seats004.geometry}
                material={materials.seats}
                position={[6.574, 1.922, 3.257]}
                rotation={[-Math.PI, 0, 0]}
                scale={0.031}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.seats005.geometry}
                material={materials.seats}
                position={[6.574, 1.922, -2.061]}
                rotation={[-Math.PI, 0, 0]}
                scale={0.031}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Railing_V004.geometry}
                material={materials.metal_05}
                position={[6.847, 3.268, 3.295]}
                rotation={[-Math.PI, 0, 0]}
                scale={-1}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Railing_V005.geometry}
                material={materials.metal_05}
                position={[6.801, 3.084, -2.056]}
                rotation={[-Math.PI, 0, 0]}
                scale={-1}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.seats006.geometry}
                material={materials.seats}
                position={[6.574, 1.922, 10.231]}
                rotation={[-Math.PI, 0, 0]}
                scale={0.031}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Railing_V006.geometry}
                material={materials.metal_05}
                position={[6.847, 3.268, 10.269]}
                rotation={[-Math.PI, 0, 0]}
                scale={-1}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.seats007.geometry}
                material={materials.seats}
                position={[6.574, 1.922, 15.64]}
                rotation={[-Math.PI, 0, 0]}
                scale={0.031}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Railing_V007.geometry}
                material={materials.metal_05}
                position={[6.801, 3.084, 15.645]}
                rotation={[-Math.PI, 0, 0]}
                scale={-1}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Railing_V008.geometry}
                material={materials.metal_05}
                position={[8.097, 4.231, 10.662]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Railing_V009.geometry}
                material={materials.metal_05}
                position={[8.097, 4.231, 2.941]}
            />
            <group
                position={[6.293, 2.745, -1.027]}
                rotation={[0, -1.571, 0]}
                scale={[1, 1, 0.735]}
            >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Door_1.geometry}
                    material={materials.Door}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Door_2.geometry}
                    material={materials.metal_02}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Door_3.geometry}
                    material={materials.Glass}
                />
            </group>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Glass001.geometry}
                material={materials.Glass}
                position={[6.31, 3.138, -2.774]}
            />
            <group
                position={[6.293, 2.745, 0.606]}
                rotation={[Math.PI, Math.PI / 2, 0]}
                scale={[-1, -1, -0.735]}
            >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Door002_1.geometry}
                    material={materials.Door}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Door002_2.geometry}
                    material={materials.metal_02}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Door002_3.geometry}
                    material={materials.Glass}
                />
            </group>
            <group
                position={[6.293, 2.745, 5.973]}
                rotation={[0, -1.571, 0]}
                scale={[1, 1, 0.735]}
            >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Door003_1.geometry}
                    material={materials.Door}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Door003_2.geometry}
                    material={materials.metal_02}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Door003_3.geometry}
                    material={materials.Glass}
                />
            </group>
            <group
                position={[6.293, 2.745, 7.605]}
                rotation={[Math.PI, Math.PI / 2, 0]}
                scale={[-1, -1, -0.735]}
            >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Door004_1.geometry}
                    material={materials.Door}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Door004_2.geometry}
                    material={materials.metal_02}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Door004_3.geometry}
                    material={materials.Glass}
                />
            </group>
            <group
                position={[6.293, 2.745, 12.959]}
                rotation={[0, -1.571, 0]}
                scale={[1, 1, 0.735]}
            >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Door005_1.geometry}
                    material={materials.Door}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Door005_2.geometry}
                    material={materials.metal_02}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Door005_3.geometry}
                    material={materials.Glass}
                />
            </group>
            <group
                position={[6.293, 2.745, 14.591]}
                rotation={[Math.PI, Math.PI / 2, 0]}
                scale={[-1, -1, -0.735]}
            >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Door006_1.geometry}
                    material={materials.Door}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Door006_2.geometry}
                    material={materials.metal_02}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Door006_3.geometry}
                    material={materials.Glass}
                />
            </group>
            <group
                position={[9.904, 2.745, -1.027]}
                rotation={[0, -1.571, 0]}
                scale={[1, 1, 0.735]}
            >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Door007_1.geometry}
                    material={materials.Door}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Door007_2.geometry}
                    material={materials.metal_02}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Door007_3.geometry}
                    material={materials.Glass}
                />
            </group>
            <group
                position={[9.904, 2.745, 0.606]}
                rotation={[Math.PI, Math.PI / 2, 0]}
                scale={[-1, -1, -0.735]}
            >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Door008_1.geometry}
                    material={materials.Door}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Door008_2.geometry}
                    material={materials.metal_02}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Door008_3.geometry}
                    material={materials.Glass}
                />
            </group>
            <group
                position={[9.904, 2.745, 5.973]}
                rotation={[0, -1.571, 0]}
                scale={[1, 1, 0.735]}
            >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Door009_1.geometry}
                    material={materials.Door}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Door009_2.geometry}
                    material={materials.metal_02}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Door009_3.geometry}
                    material={materials.Glass}
                />
            </group>
            <group
                position={[9.904, 2.745, 7.605]}
                rotation={[Math.PI, Math.PI / 2, 0]}
                scale={[-1, -1, -0.735]}
            >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Door010_1.geometry}
                    material={materials.Door}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Door010_2.geometry}
                    material={materials.metal_02}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Door010_3.geometry}
                    material={materials.Glass}
                />
            </group>
            <group
                position={[9.904, 2.745, 12.959]}
                rotation={[0, -1.571, 0]}
                scale={[1, 1, 0.735]}
            >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Door011_1.geometry}
                    material={materials.Door}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Door011_2.geometry}
                    material={materials.metal_02}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Door011_3.geometry}
                    material={materials.Glass}
                />
            </group>
            <group
                position={[9.904, 2.745, 14.591]}
                rotation={[Math.PI, Math.PI / 2, 0]}
                scale={[-1, -1, -0.735]}
            >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Door012_1.geometry}
                    material={materials.Door}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Door012_2.geometry}
                    material={materials.metal_02}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Door012_3.geometry}
                    material={materials.Glass}
                />
            </group>
            <group
                position={[6.293, 2.745, 17.408]}
                rotation={[Math.PI, Math.PI / 2, 0]}
                scale={[-1, -1, -0.735]}
            >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Door013_1.geometry}
                    material={materials.Door}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Door013_2.geometry}
                    material={materials.metal_02}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Door013_3.geometry}
                    material={materials.Glass}
                />
            </group>
            <group
                position={[9.904, 2.745, 17.408]}
                rotation={[Math.PI, Math.PI / 2, 0]}
                scale={[-1, -1, -0.735]}
            >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Door014_1.geometry}
                    material={materials.Door}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Door014_2.geometry}
                    material={materials.metal_02}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Door014_3.geometry}
                    material={materials.Glass}
                />
            </group>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Glass002.geometry}
                material={materials.Glass}
                position={[6.31, 3.138, 3.842]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Glass003.geometry}
                material={materials.Glass}
                position={[6.31, 3.138, 10.829]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Glass004.geometry}
                material={materials.Glass}
                position={[6.31, 3.138, 15.639]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Glass005.geometry}
                material={materials.Glass}
                position={[9.908, 3.138, -2.774]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Glass006.geometry}
                material={materials.Glass}
                position={[9.908, 3.138, 3.842]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Glass007.geometry}
                material={materials.Glass}
                position={[9.908, 3.138, 10.829]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Glass012.geometry}
                material={materials.Glass}
                position={[9.908, 3.138, 15.639]}
            />
            <group position={[7.72, 2.745, -4.724]} scale={[1, 1, 0.735]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Door015_1.geometry}
                    material={materials.Door}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Door015_2.geometry}
                    material={materials.metal_02}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Door015_3.geometry}
                    material={materials.Glass}
                />
            </group>
            <group position={[7.72, 2.745, 18.318]} scale={[1, 1, 0.735]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Door016.geometry}
                    material={materials.Door}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Door016_1.geometry}
                    material={materials.metal_02}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Door016_2.geometry}
                    material={materials.Glass}
                />
            </group>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Glass008.geometry}
                material={materials.Glass}
                position={[9.288, 3.298, 18.334]}
                rotation={[0, 1.571, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Glass009.geometry}
                material={materials.Glass}
                position={[6.912, 3.298, 18.334]}
                rotation={[0, 1.571, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Glass010.geometry}
                material={materials.Glass}
                position={[9.288, 3.298, -4.716]}
                rotation={[0, 1.571, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Glass011.geometry}
                material={materials.Glass}
                position={[6.912, 3.298, -4.716]}
                rotation={[0, 1.571, 0]}
            />
        </group>
    );
}

useGLTF.preload("/Metro_AR.glb");
